//package solutionsHackerRank;

import java.util.Scanner;

public class The_Hurdle_Race {

	public static void main(String[] args) {
		        Scanner sc=new Scanner(System.in);
		        int n=sc.nextInt();
		        int k=sc.nextInt();
		        int arr[]=new int[n];
		        for(int i=0; i<n; i++){
		            arr[i]=sc.nextInt();
		        }
		        sc.close();
		        int greatest=arr[0];
		        for(int i=1; i<n; i++){
		            if(arr[i]>greatest){
		                greatest=arr[i];
		            }
		        }
		        if((greatest-k)>0) {
		        System.out.println(greatest-k);
		    }
		        else {
		        	System.out.println(0);
		        }
	}
}


